// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4FSLulj7RhYuGbwSwhk9IhtgdFR6lco',
    appId: '1:521448843417:web:16a137b9774f934ebab008',
    messagingSenderId: '521448843417',
    projectId: 'karyana-ae153',
    authDomain: 'karyana-ae153.firebaseapp.com',
    databaseURL: 'https://karyana-ae153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karyana-ae153.appspot.com',
    measurementId: 'G-528C7XVTCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzRUOhxAdozoFz6s7aYI8tJDW0mhjxAs',
    appId: '1:521448843417:android:5ffd36f95cfedb6dbab008',
    messagingSenderId: '521448843417',
    projectId: 'karyana-ae153',
    databaseURL: 'https://karyana-ae153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karyana-ae153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPyFnHxV1NxWeaxzB1gXNRpLd97PucjaA',
    appId: '1:521448843417:ios:04277cda6c8822a8bab008',
    messagingSenderId: '521448843417',
    projectId: 'karyana-ae153',
    databaseURL: 'https://karyana-ae153-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karyana-ae153.appspot.com',
    iosClientId: '521448843417-n8crh510nu5vp621evt998222efrdjd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.karyana',
  );
}
